In [114]:
!pip install -q transformers datasets accelerate evaluate scikit-learn pyarrow

In [115]:
import pandas as pd

from datasets import Dataset
from transformers import AutoTokenizer

In [116]:
BIAS_PATH = "/content/drive/MyDrive/AI-News-Perspective-Analyzer/datasets/article-bias/train_clean.parquet"

STANCE_PATH = "/content/drive/MyDrive/AI-News-Perspective-Analyzer/datasets/stance/train_clean.csv"

bias_df = pd.read_parquet(BIAS_PATH)

stance_df = pd.read_csv(
    STANCE_PATH,
    encoding="latin1"
)

In [117]:
print(bias_df.columns)

print()

print(stance_df.columns)

Index(['topic', 'source', 'bias', 'url', 'title', 'date', 'authors', 'content',
       'content_original', 'source_url', 'bias_text', 'ID', 'content_length'],
      dtype='object')

Index(['Body ID', 'articleBody', 'Headline', 'Stance', 'body_length'], dtype='object')

In [118]:
bias_df = bias_df[["content", "bias"]]

bias_df = bias_df.rename(
    columns={
        "content": "text",
        "bias": "label"
    }
)

bias_df.head()

                                                text  label
0  This happens for different reasons , but a key...      0
1  LISTEN TO ARTICLE 5:37 SHARE THIS ARTICLE Shar...      1
2  The Pentagon ’ s top general said Tuesday that...      2
3  Story highlights A Russian lawmaker says Russi...      0
4  Iran 's latest crackdown on freedom includes l...      2

In [119]:
stance_map = {
    "agree": 0,
    "discuss": 1,
    "disagree": 2,
    "unrelated": 3
}

stance_df["label"] = stance_df["Stance"].map(stance_map)

In [120]:
stance_df["text"] = (
    "Headline: "
    + stance_df["Headline"].astype(str)
    + " Body: "
    + stance_df["articleBody"].astype(str)
)

In [121]:
stance_df = stance_df[["text", "label"]]

stance_df.head()

                                                text  label
0  Headline: Soldier shot, Parliament locked down...      3
1  Headline: Tourist dubbed ÂSpider ManÂ after ...      3
2  Headline: Luke Somers 'killed in failed rescue...      3
3  Headline: BREAKING: Soldier shot at War Memori...      3
4  Headline: Giant 8ft 9in catfish weighing 19 st...      3

In [122]:
print(type(stance_df.loc[0, "text"]))

print(type(bias_df.loc[0, "text"]))

<class 'str'>
<class 'str'>

In [123]:
bias_dataset = Dataset.from_pandas(
    bias_df,
    preserve_index=False
)

stance_dataset = Dataset.from_pandas(
    stance_df,
    preserve_index=False
)

In [124]:
MODEL_NAME = "roberta-base"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME
)

In [125]:
def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=512
    )

In [126]:
tokenized_bias = bias_dataset.map(
    tokenize,
    batched=True
)

Map:   0%|          | 0/29258 [00:00<?, ? examples/s]

In [127]:
tokenized_stance = stance_dataset.map(
    tokenize,
    batched=True
)

Map:   0%|          | 0/48437 [00:00<?, ? examples/s]

In [128]:
print(tokenized_bias[0])

{'text': 'This happens for different reasons , but a key element is the vicious cycle between holding strong attitudes on an issue and something called “ selective perception. ” Essentially , the stronger your views are on an issue like Trump ’ s impeachment , the more likely you are to attend more carefully to information that supports your views and to ignore or disregard information that contradicts them . Consuming more belief-consistent information will , in turn , increase your original support or disapproval for impeachment , which just fortifies your attitudes . So , no , not much change will be seen in the minds of the 33 percent .\nExcept , maybe . One of the more interesting findings from research on attitude change is that our more important , self-defining attitudes do not seem to change incrementally , a little at a time , but they can change dramatically , from one extreme to another . Typically , when others try to change our views on important issues that we hold firmly , their attempts to persuade us with facts and figures end up bolstering our original attitudes or pushing us out to even further extremes . But strong attitudes can experience what psychologists call “ threshold-effect changes. ” Over time , when we are exposed to information contradicting our attitudes , that information—even if we ignore , discount or deny it—can seep into our thinking and accumulate to a point where , across some threshold , people radically change their views to the opposite side of the spectrum . In other words , nothing much changes until everything changes .\nThese jumps from one extreme attitude to another on self-defining issues are not uncommon , and have been seen with former skinheads turned tolerance trainers , peace activists turned violent militants , and religious zealots turned atheists . This type of drastic transformation is , of course , hard to predict , and it can be triggered by seemingly insignificant events ( the tipping point for one skinhead was when his black co-worker tossed him half of his submarine sandwich when he had no lunch ) . But it typically occurs after repeated exposure to information contradicting their attitudes .\nSo , yes , it is possible that if some of the testimonies in the hearings are experienced by true believers ( at either extreme ) as counter to their beliefs but also persuasive , this information can plant seeds of a different point of view , that might , someday , lead to a big change . Still , this is unlikely to happen very soon .\nMinds , however , can change among the vast majority of people who don ’ t hold extreme views . A recent study by the nonpartisan group More in Common found that about 67 percent of moderate Americans on both sides of the political divide—a group the authors of the study call “ the exhausted majority ” —are fed up with our current dysfunction , despise the contemptuous state of polarization we are in , and are eager to find ways to talk , compromise and work together again . These folks , particularly the 26 percent of moderates who are politically disengaged and thus are much less identified with either tribe , can be swayed . Of course , this assumes that they are not so burned out by the vitriol of our politics that they are unwilling to devote some attention to information coming out of the hearings .\nResearch suggests a few basic strategies for changing minds that are , well , changeable . First , immediately establishing the credibility of the witnesses—to both progressives and conservatives —is paramount . For example , the introductions of the witnesses should emphasize their merits for both the left and the right to see . Second , logic and evidence can matter when they are clearly laid out , compelling and derived from trusted sources . Third , moving testimony by witnesses about the profound moral dilemmas they faced in coming forward , and any specific threats they experienced to their and their family ’ s physical safety , can help to humanize otherwise dry , technical testimony and move the listener . And finally , because most viewers tend to lean either red or blue ( even though they are “ exhausted ” ) and so will view the proceedings to some degree through their team ’ s lens , it is critical for the lawmakers to choose to emphasize just a few takeaway points , and then to stress the urgency and importance of the viewers ’ attention to them . This can serve to move viewers from their more automatic , heuristic modes of cognitive processing to more intentional , systematic modes , where they will be more likely to take in new information and learn .\nBut here is a caution for our leaders in Congress on both sides . Clearly , by many accounts , America is more polarized , anxious and exhausted by our political climate today than ever before . No , this is not all Congress ’ doing , but many in Washington are playing their part . The resulting rise in the toxicity of our culture is such that today 86 percent of Americans are seriously concerned that our divisions will soon lead to violence .\nSo , as our Republican and Democratic members of Congress prepare for the public hearings—ready themselves to make their case and score points and change minds—they should understand what is at stake . A narrow focus on short wins today can bring devastating outcomes tomorrow . Of course , members of Congress have a job to do to reveal the truth and share the facts with the American public . But our social fabric is stretched to the limit , and the future of our society , in the form of our basic capacities for compassion , connection and shared humanity across our divide , is on the line . The impeachment hearings ’ primary audience—the 67 percent ( not base voters ) —is persuadable through credibility , logic and evidence . This is a chance for lawmakers to plant seeds for changing minds in the future . So , please , for our nation ’ s sake , rise to your best selves .\nAs someone who knew something about divisions once wrote , “ We are not enemies , but friends . We must not be enemies . Though passion may have strained , it must not break our bonds of affection . The mystic chords of memory will swell when again touched , as surely they will be , by the better angels of our nature. ” Come Wednesday , lawmakers will need to find a way to make their public case effectively , while not inflaming our already heightened sense of contempt and enmity for the other side . In the long run , this is all that will matter .', 'label': 0, 'input_ids': [0, 713, 2594, 13, 430, 2188, 2156, 53, 10, 762, 7510, 16, 5, 16339, 4943, 227, 1826, 670, 15764, 15, 41, 696, 8, 402, 373, 44, 48, 21921, 10518, 4, 44, 46, 30588, 2156, 5, 3651, 110, 2728, 32, 15, 41, 696, 101, 140, 44, 27, 579, 14097, 2156, 5, 55, 533, 47, 32, 7, 2725, 55, 7015, 7, 335, 14, 4548, 110, 2728, 8, 7, 8861, 50, 21034, 335, 14, 37820, 106, 479, 9051, 20016, 55, 6563, 12, 10998, 21464, 335, 40, 2156, 11, 1004, 2156, 712, 110, 1461, 323, 50, 32129, 13, 14097, 2156, 61, 95, 15016, 10687, 110, 15764, 479, 407, 2156, 117, 2156, 45, 203, 464, 40, 28, 450, 11, 5, 7283, 9, 5, 2357, 135, 479, 50118, 45035, 2156, 2085, 479, 509, 9, 5, 55, 2679, 4139, 31, 557, 15, 6784, 464, 16, 14, 84, 55, 505, 2156, 1403, 12, 9232, 6074, 15764, 109, 45, 2045, 7, 464, 30401, 2368, 2156, 10, 410, 23, 10, 86, 2156, 53, 51, 64, 464, 8617, 2156, 31, 65, 5004, 7, 277, 479, 18410, 2156, 77, 643, 860, 7, 464, 84, 2728, 15, 505, 743, 14, 52, 946, 10523, 2156, 49, 3881, 7, 15425, 201, 19, 4905, 8, 2415, 253, 62, 31993, 2961, 84, 1461, 15764, 50, 3784, 201, 66, 7, 190, 617, 31823, 479, 125, 670, 15764, 64, 676, 99, 33208, 486, 44, 48, 11543, 12, 26715, 1022, 4, 44, 46, 2306, 86, 2156, 77, 52, 32, 4924, 7, 335, 28204, 154, 84, 15764, 2156, 14, 335, 578, 12963, 114, 52, 8861, 2156, 6720, 50, 7631, 24, 578, 7424, 842, 2462, 88, 84, 2053, 8, 29196, 7, 10, 477, 147, 2156, 420, 103, 11543, 2156, 82, 26396, 464, 49, 2728, 7, 5, 5483, 526, 9, 5, 8576, 479, 96, 97, 1617, 2156, 1085, 203, 1022, 454, 960, 1022, 479, 50118, 4528, 13855, 31, 65, 5004, 6784, 7, 277, 15, 1403, 12, 9232, 6074, 743, 32, 45, 18186, 2156, 8, 33, 57, 450, 19, 320, 3024, 16560, 1224, 12352, 17120, 2156, 1987, 4826, 1224, 4153, 5496, 2156, 8, 3458, 33103, 5992, 1224, 45008, 479, 152, 1907, 9, 19167, 7791, 16, 2156, 9, 768, 2156, 543, 7, 7006, 2156, 8, 24, 64, 28, 7544, 30, 6590, 33710, 1061, 36, 5, 22737, 477, 13, 65, 3024, 3628, 21, 77, 39, 909, 1029, 12, 23589, 14937, 123, 457, 9, 39, 20224, 15649, 77, 37, 56, 117, 4592, 4839, 479, 125, 24, 3700, 11493, 71, 6636, 4895, 7, 335, 28204, 154, 49, 15764, 479, 50118, 2847, 2156, 4420, 2156, 24, 16, 678, 14, 114, 103, 9, 5, 36708, 11, 5, 9445, 32, 2984, 30, 1528, 29446, 36, 23, 1169, 5004, 4839, 25, 3231, 7, 49, 9734, 53, 67, 38245, 2156, 42, 335, 64, 2195, 9775, 9, 10, 430, 477, 9, 1217, 2156, 14, 429, 2156, 23090, 2156, 483, 7, 10, 380, 464, 479, 3180, 2156, 42, 16, 3752, 7, 1369, 182, 1010, 479, 50118, 34875, 29, 2156, 959, 2156, 64, 464, 566, 5, 4714, 1647, 9, 82, 54, 218, 44, 27, 326, 946, 5004, 2728, 479, 83, 485, 892, 30, 5, 25167, 333, 901, 2], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [129]:
print(tokenized_stance[0])

{'text': 'Headline: Soldier shot, Parliament locked down after gunfire erupts at war memorial Body: A small meteorite crashed into a wooded area in Nicaragua\'s capital of Managua overnight, the government said Sunday. Residents reported hearing a mysterious boom that left a 16-foot deep crater near the city\'s airport, the Associated Press reports. \r\n\r\nGovernment spokeswoman Rosario Murillo said a committee formed by the government to study the event determined it was a "relatively small" meteorite that "appears to have come off an asteroid that was passing close to Earth." House-sized asteroid 2014 RC, which measured 60 feet in diameter, skimmed the Earth this weekend, ABC News reports. \r\nMurillo said Nicaragua will ask international experts to help local scientists in understanding what happened.\r\n\r\nThe crater left by the meteorite had a radius of 39 feet and a depth of 16 feet,  said Humberto Saballos, a volcanologist with the Nicaraguan Institute of Territorial Studies who was on the committee. He said it is still not clear if the meteorite disintegrated or was buried.\r\n\r\nHumberto Garcia, of the Astronomy Center at the National Autonomous University of Nicaragua, said the meteorite could be related to an asteroid that was forecast to pass by the planet Saturday night.\r\n\r\n"We have to study it more because it could be ice or rock," he said.\r\n\r\nWilfried Strauch, an adviser to the Institute of Territorial Studies, said it was "very strange that no one reported a streak of light. We have to ask if anyone has a photo or something."\r\n\r\nLocal residents reported hearing a loud boom Saturday night, but said they didn\'t see anything strange in the sky.\r\n\r\n"I was sitting on my porch and I saw nothing, then all of a sudden I heard a large blast. We thought it was a bomb because we felt an expansive wave," Jorge Santamaria told The Associated Press.\r\n\r\nThe site of the crater is near Managua\'s international airport and an air force base. Only journalists from state media were allowed to visit it.', 'label': 3, 'input_ids': [0, 28873, 1902, 35, 29845, 738, 6, 3879, 5930, 159, 71, 14211, 24850, 29, 23, 997, 7041, 13048, 35, 83, 650, 12505, 1459, 6050, 88, 10, 5627, 196, 443, 11, 25687, 18, 812, 9, 1554, 1073, 4324, 4427, 6, 5, 168, 26, 395, 4, 10073, 431, 1576, 10, 12754, 8600, 14, 314, 10, 545, 12, 2917, 1844, 30702, 583, 5, 343, 18, 3062, 6, 5, 1562, 977, 690, 4, 1437, 50121, 50118, 50121, 50118, 28747, 3582, 4168, 7718, 7273, 6491, 26, 10, 1540, 4829, 30, 5, 168, 7, 892, 5, 515, 3030, 24, 21, 10, 22, 5982, 10481, 650, 113, 12505, 1459, 14, 22, 3340, 12541, 7, 33, 283, 160, 41, 26236, 14, 21, 3133, 593, 7, 3875, 72, 446, 12, 8407, 26236, 777, 19682, 6, 61, 9550, 1191, 1730, 11, 26089, 6, 28772, 4567, 5, 3875, 42, 983, 6, 3943, 491, 690, 4, 1437, 50121, 50118, 32405, 6491, 26, 25687, 40, 1394, 758, 2320, 7, 244, 400, 4211, 11, 2969, 99, 1102, 4, 50121, 50118, 50121, 50118, 133, 30702, 314, 30, 5, 12505, 1459, 56, 10, 29943, 9, 3191, 1730, 8, 10, 5581, 9, 545, 1730, 6, 1437, 26, 289, 9936, 560, 6371, 1250, 366, 6, 10, 31783, 6393, 19, 5, 43527, 7372, 2534, 9, 42243, 17707, 9307, 54, 21, 15, 5, 1540, 4, 91, 26, 24, 16, 202, 45, 699, 114, 5, 12505, 1459, 32654, 8358, 50, 21, 8203, 4, 50121, 50118, 50121, 50118, 725, 9936, 560, 6603, 6, 9, 5, 24494, 13604, 824, 23, 5, 496, 9496, 24239, 589, 9, 25687, 6, 26, 5, 12505, 1459, 115, 28, 1330, 7, 41, 26236, 14, 21, 1914, 7, 1323, 30, 5, 5518, 378, 363, 4, 50121, 50118, 50121, 50118, 113, 170, 33, 7, 892, 24, 55, 142, 24, 115, 28, 2480, 50, 3152, 60, 37, 26, 4, 50121, 50118, 50121, 50118, 28886, 21209, 13893, 4272, 6, 41, 4988, 7, 5, 2534, 9, 42243, 17707, 9307, 6, 26, 24, 21, 22, 5525, 7782, 14, 117, 65, 431, 10, 3963, 9, 1109, 4, 166, 33, 7, 1394, 114, 1268, 34, 10, 1345, 50, 402, 72, 50121, 50118, 50121, 50118, 24476, 1196, 431, 1576, 10, 7337, 8600, 378, 363, 6, 53, 26, 51, 399, 75, 192, 932, 7782, 11, 5, 6360, 4, 50121, 50118, 50121, 50118, 113, 100, 21, 2828, 15, 127, 20609, 8, 38, 794, 1085, 6, 172, 70, 9, 10, 7207, 38, 1317, 10, 739, 7814, 4, 166, 802, 24, 21, 10, 4840, 142, 52, 1299, 41, 21734, 4605, 60, 15580, 8550, 424, 8954, 174, 20, 1562, 977, 4, 50121, 50118, 50121, 50118, 133, 1082, 9, 5, 30702, 16, 583, 1554, 1073, 4324, 18, 758, 3062, 8, 41, 935, 1370, 1542, 4, 4041, 4225, 31, 194, 433, 58, 1220, 7, 825, 24, 4, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [130]:
tokenized_bias.save_to_disk(
    "/content/drive/MyDrive/AI-News-Perspective-Analyzer/tokenized_bias"
)

tokenized_stance.save_to_disk(
    "/content/drive/MyDrive/AI-News-Perspective-Analyzer/tokenized_stance"
)

Saving the dataset (0/1 shards):   0%|          | 0/29258 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/48437 [00:00<?, ? examples/s]